
import type { Scenario } from './types';

// This file will be emptied as scenarios are now managed in Firestore.
// You might want to run a one-time script to migrate these to your Firestore database
// or manually create them using your new Scenario Editor.

export const scenarios: Scenario[] = [
  // {
  //   id: '1', // This ID will be auto-generated by Firestore or manually set
  //   title: 'Hate-Speech',
  //   kurzbeschreibung: 'Beschimpfungen & Grenzüberschreitungen im Chat.',
  //   langbeschreibung: 'In diesem Szenario wird ein Online-Diskurs simuliert, der durch Hate-Speech, persönliche Angriffe und verbale Grenzüberschreitungen gekennzeichnet ist. Teilnehmende lernen, solche Situationen zu erkennen, darauf zu reagieren und Strategien zur Deeskalation oder Meldung zu entwickeln.',
  //   // defaultBots and standardRollen will be derived from defaultBotsConfig.length and humanRolesConfig.length
  //   iconName: 'ShieldAlert',
  //   tags: ['Konflikt', 'Respekt', 'Online-Sicherheit'],
  //   previewImageUrl: 'https://placehold.co/600x400.png',
  //   lernziele: [
  //       "Hate-Speech erkennen und definieren können.",
  //       "Strategien zur Reaktion auf Hate-Speech entwickeln (Gegenrede, Melden, Ignorieren).",
  //       "Emotionale Auswirkungen von Hate-Speech auf Betroffene verstehen."
  //   ],
  //   defaultBotsConfig: [
  //     { id: '1-prov-0', name: "Provokateur Alpha", personality: 'provokateur', avatarFallback: 'PA', currentEscalation: 1, isActive: true, initialMission: "Störe die Diskussion mit aggressiven Kommentaren." },
  //     { id: '1-vert-1', name: "Verteidiger Beta", personality: 'verteidiger', avatarFallback: 'VB', currentEscalation: 0, isActive: true, initialMission: "Tritt für einen respektvollen Umgang ein und widersprich dem Provokateur." },
  //   ],
  //   humanRolesConfig: [
  //       { id: "1-opfer-0", name: "Zielperson der Angriffe", description: "Du hast einen neutralen Kommentar gepostet und wirst nun Ziel von verbalen Attacken. Versuche, dich zu behaupten oder Hilfe zu suchen." },
  //       { id: "1-unterstuetzer-0", name: "Unterstützer*in", description: "Du beobachtest die Angriffe auf die Zielperson. Entscheide, ob und wie du eingreifst, um zu helfen oder zu deeskalieren." },
  //       { id: "1-beobachter-0", name: "Stiller Beobachter", description: "Du liest im Chat mit, greifst aber zunächst nicht aktiv ein. Überlege, was deine Zurückhaltung bewirkt und wann ein Eingreifen für dich sinnvoll wäre." }
  //   ]
  // },
  // ... other scenarios can be migrated similarly
];

// IMPORTANT: To migrate your existing scenarios, you can:
// 1. Manually re-enter them using the new Scenario Editor once it's fully functional with Firestore.
// 2. Write a one-time script (e.g., a Node.js script using the Firebase Admin SDK) to read this array
//    and write each scenario object as a new document to your Firestore "scenarios" collection.
//    Remember to add `createdAt: serverTimestamp()` and `updatedAt: serverTimestamp()` for new documents.
